### ISSUE TITLE
Change width of front page

### ISSUE THREAD

**Issue by annehilliger** [weareopen/learnwith#4]
if I change the with of the content of front padge the full-width elements lose their full-width too, this is not supposed to happen and I don't know how do do it

**Comment by LauraHilliger** [comment]
I adjusted the elements to be inside of sections, you should have a look at each section > section structure and determine the width you want. It's pixel not percentage, so I set to a standard of 1024px as a max-width. You might like to check the alignment and things too because I just did the structural stuff
